/*
SQLyog Community v11.12 (64 bit)
MySQL - 5.0.41-log 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `product2` (
	`ProductID` int (6),
	`ProductName` varchar (105),
	`ProductCaption` varchar (765),
	`ProductPrice` int (5),
	`ImageURL` varchar (765),
	`ProductType` varchar (105),
	`ProductDescription` text 
); 
insert into `product2` (`ProductID`, `ProductName`, `ProductCaption`, `ProductPrice`, `ImageURL`, `ProductType`, `ProductDescription`) values('1','Apple EarPods','Earpods created by Apple.','49','Images/AppleEarPods.jpg','Earphones','Unlike traditional, circular earbuds, the design of the new Apple EarPods is defined by the geometry of the ear. Which makes them more comfortable for more people than any other earbud-style headphone.\r\n\r\nThe speakers inside Apple EarPods have been engineered to minimise sound loss and maximise sound output. So you get highquality audio that\'s just as impressive as what you\'d hear from more expensive headphones.');
insert into `product2` (`ProductID`, `ProductName`, `ProductCaption`, `ProductPrice`, `ImageURL`, `ProductType`, `ProductDescription`) values('2','Jabra Elite Active 65t','Completly wireless earphones created by Jabra.','250','Images/top_earbuds.png','Earphones','Engineered for true wireless music, calls and sport. No strings attached.\r\n\r\nA fit that\'s snug and secure:\r\nEnjoy an actively lifestyle with secure fitting earbuds that provide dependable in-ear stability.\r\n\r\nBuilt for active lifestyles:\r\nJabra Elite Active 65t features an IP56 rating. Wherever your day takes you, and whatever your activity, it won\'t get in the way of enjoying sports, music and calls.');
insert into `product2` (`ProductID`, `ProductName`, `ProductCaption`, `ProductPrice`, `ImageURL`, `ProductType`, `ProductDescription`) values('3','Jaybird X3','Wireless earbuds attached with a cable to eachother.','150','Images/Jaybird_x3.jpg','Earphones','Featuring noise cancelling and splash-proof design, the WI-SP600N is a discreet, comfortable headphone ideal for both working out and the daily commute. Made for movement, this headphone offers Ambient Sound Mode; keeping you aware of your surroundings, Smartphone App control, hands-free calls, long battery life and high quality music reproduction.');
insert into `product2` (`ProductID`, `ProductName`, `ProductCaption`, `ProductPrice`, `ImageURL`, `ProductType`, `ProductDescription`) values('4','Bose QC25','Noise-cancelling headphones that can be both wired or wireless.','350','Images/Bose_QuietComfort_25.png','Headphones','Despite showing their age, the Bose QuietComfort 25 offer a deluxe set of noise-cancelling headphones that delivers an unparalleled audio experience that\'s well worth the price of admission.');
insert into `product2` (`ProductID`, `ProductName`, `ProductCaption`, `ProductPrice`, `ImageURL`, `ProductType`, `ProductDescription`) values('5','Sennheiser HD 4.30G','Closed back and Over Ear, Galaxy compatible.','189','Images/Sennheiser-HD-4.30G.jpg','Headphones','The HD 4.30 lets you experience the power and the quality of the Sennheiser sound anytime, anywhere. Featuring a closed-back over-ear design it creates an exceptional soundscape with precise acoustic response and a rich dynamic bass.');
insert into `product2` (`ProductID`, `ProductName`, `ProductCaption`, `ProductPrice`, `ImageURL`, `ProductType`, `ProductDescription`) values('6','Sony WI-SP600N','Wireless, Noise Cancelling Extra Bass headphones.','199','Images/Sony-WI-SP600N.jpg','Earphones','Featuring noise cancelling and splash-proof design, the WI-SP600N is a discreet, comfortable headphone ideal for both working out and the daily commute. Made for movement, this headphone offers Ambient Sound Mode; keeping you aware of your surroundings, Smartphone App control, hands-free calls, long battery life and high quality music reproduction.');
insert into `product2` (`ProductID`, `ProductName`, `ProductCaption`, `ProductPrice`, `ImageURL`, `ProductType`, `ProductDescription`) values('7','JBL E45BT','Up to 16-hour battery life Two-hour recharge time.','149','Images/JBL-E45BT.jpg','Headphones','JBL E45BT on-ear wireless headphones bring the signature sound of JBL right to your ears. The E45BT is one of our most versatile products ever, featuring up to 16 hours of battery life, an innovative, stylish fabric headband and ergonomic on-ear design. This means that your entertainment continues and your fun factor gets amped up no matter what you are doing. Working, commuting, or just making your way around town.');
insert into `product2` (`ProductID`, `ProductName`, `ProductCaption`, `ProductPrice`, `ImageURL`, `ProductType`, `ProductDescription`) values('8','Apple AirPods','More than 24-hour battery life with Charging Case.','239','Images/Airpods.jpg','Earphones','AirPods will forever change the way you use headphones. Whenever you pull your AirPods out of the charging case, they instantly turn on and connect to your iPhone, Apple Watch, iPad or Mac. Audio automatically plays as soon as you put them in your ears and pauses when you take them out. To adjust the volume, change the song, make a call or even get directions, just double tap to activate Siri.');
insert into `product2` (`ProductID`, `ProductName`, `ProductCaption`, `ProductPrice`, `ImageURL`, `ProductType`, `ProductDescription`) values('9','Soundbox X1','A sound that will open your outdoors.','120','Images/Soundbox.png','Speaker','The Soundbox is the most portable in our durable, outdoor speaker family, crafted with sustainable Cork to be as natural as its intended environment. The speaker series is designed for outdoor use with rugged, waterproof and dust-proof materials. Each Speaker Box boasts a 10-hour battery life with wireless dual-speaker pairing capability and speakerphone functionality. Quick charge it with the provided cable between uses.');
insert into `product2` (`ProductID`, `ProductName`, `ProductCaption`, `ProductPrice`, `ImageURL`, `ProductType`, `ProductDescription`) values('10','JBL Xtreme','Hear the bass, feel the bass, see the bass. ','270','Images/JBL_speaker.png','Speaker','JBL Xtreme 2 is the ultimate portable Bluetooth speaker that effortlessly delivers dynamic and immersive stereo sound. The speaker is armed with four drivers, two JBL Bass Radiators, a rechargeable 10,000mAh Li-ion battery supporting up to 15 hours of playtime. On top of these, the speaker carries a convenient USB charge out.');
insert into `product2` (`ProductID`, `ProductName`, `ProductCaption`, `ProductPrice`, `ImageURL`, `ProductType`, `ProductDescription`) values('11','Ultimate Ears BOOM 2','Rage, riot, party and play the music you love, out loud.','139','Images/UE_speaker.png','Speaker','UE BOOM 2 is the 360-degree wireless speaker that blasts loud, insanely great sound with deep, powerful bass in every direction - everywhere you go. It was designed to get wet, muddy and beat up. It\'s waterproof, shockproof and crafted from the sexiest and most uninhibited premium materials in the known universe. Throw it on your bike, clip it to your bag or just grab it and go â€“ get it wet, get it muddy and party onward into the unknown.');
insert into `product2` (`ProductID`, `ProductName`, `ProductCaption`, `ProductPrice`, `ImageURL`, `ProductType`, `ProductDescription`) values('12','Sennheiser HD 6XX','Refreshed Aesthetic, Improved Utility','249','Images/Sennheiser_HD650.png','Headphones','If you know audio gear, you know the Sennheiser HD 650. The companyâ€™s flagship from 2003 to 2009, this open-back headphone has shown serious staying power. Praised for its richly detailed, effortlessly enjoyable sound, it remains one of the most talked-about products on Head-Fi todayâ€”and is still widely considered among the best headphones under $1,000.');
insert into `product2` (`ProductID`, `ProductName`, `ProductCaption`, `ProductPrice`, `ImageURL`, `ProductType`, `ProductDescription`) values('88','Sonos','The Smart Speaker for Music Lovers.','189','Images/Sonos.png','Speaker','Sonos One blends great sound with Amazon Alexa, the easy-to-use voice service, for hands-free control of your music and more. Use your voice to play songs while you cook. Tell Alexa to turn the volume up while youâ€™re in the shower. You can even request your favourite lullaby when youâ€™re tucking the kids in.');
